### ISSUE TITLE
[NEW] Origin and Suite tags for APT repo

### ISSUE THREAD

**Issue by Birdie0** [redis/redis-debian#18] opened 2023-10-22 10:34 UTC
**The problem/use-case that the feature addresses**

At the moment `packages.redis.io` apt repo doesn't have `Origin` and `Suite` filled (first is missing, second is blank), that can be confirmed by checking its `_InRelease` file:

```sh
$ grep -E '^(Origin|Suite):' /var/lib/apt/lists/packages.redis.io_deb_dists_jammy_InRelease
Suite:
```

Because of that it can't be configured for using with [unattended upgrades](https://wiki.debian.org/UnattendedUpgrades).

**Description of the feature**

Having `Origin` and `Suite` present would allow to use auto-updates with [unattended upgrades](https://wiki.debian.org/UnattendedUpgrades).

**Alternatives you've considered**

Manual upgrades, downgrading to package provided in Ubuntu default repo or using Docker instance with [Watchtower](https://github.com/containrrr/watchtower)

**Additional information**

Those are present in official Ubuntu repos, also 3rd-party ones, like Launchpad PPAs, PostgreSQL and others.

Example:
```sh
$ grep -E '^(Origin|Suite):' /var/lib/apt/lists/apt.postgresql.org_pub_repos_apt_dists_jammy-pgdg_InRelease
Origin: apt.postgresql.org
Suite: jammy-pgdg
```

**Comment by yossigo** [comment] 2023-10-22 15:27
Duplicate of #17

**Closed** 2023-11-02 08:55 UTC
